### ISSUE TITLE
Dashboard toont "dubbelingen"

### ISSUE THREAD

**Issue by Geert-Jan-DH** [maykinmedia/open-zaaktypebeheer#57]
Het dasboard toont zaaktypen "dubbel" die waarschijnlijk niet echt dubbel zijn, omdat ze een andere periode actief waren. Maar dat zie je dus niet. En dan zijn ze dus dubbel en kun je niet kiezen.

<img width="213" alt="image" src="https://github.com/maykinmedia/open-zaaktypebeheer/assets/129515205/efc85efa-b59a-4f9d-99be-0eff11197af6">

**Comment by SilviaAmAm** [comment]
Oplossing:
- [ ] Toon als default de kolommen 'begin geldigheid' en 'einde geldigheid'
- [ ] Voeg in de backend een veld 'actief' => Dit is 'true' als de datum van vandaag is beginGeldigheid <= vandaag < eindeGeldigheid.
- [ ] In de frontend filter als default voor 'actieve' zaaktypen
